#ifndef TAREA2_CONSTANTS_H
#define TAREA2_CONSTANTS_H

#include <sys/reg.h>

// Defines
#define	SUCCESS 0
#define	FAILURE 1
#define	IN_PROGESS 2

#define ARGS_QUANTITY 6
#ifdef __x86_64__
#define VALID_ARCH 1
#define SYSCALLS_QUANTITY 336
#define REG_SYSCALL_NUMBER  ORIG_RAX
#define REG_SYSCALL_RETURN RAX
#define REG_SYSCALL_ARG1 RDI
#define REG_SYSCALL_ARG2 RSI
#define REG_SYSCALL_ARG3 RDX
#define REG_SYSCALL_ARG4 R10
#define REG_SYSCALL_ARG5 R8
#define REG_SYSCALL_ARG6 R9
#else
#ifdef __i386__
#define VALID_ARCH 1
#define SYSCALLS_QUANTITY 385
#define REG_SYSCALL_NUMBER  ORIG_EAX
#define REG_SYSCALL_RETURN EAX
#define REG_SYSCALL_ARG1 EBX
#define REG_SYSCALL_ARG2 ECX
#define REG_SYSCALL_ARG3 EDX
#define REG_SYSCALL_ARG4 ESI
#define REG_SYSCALL_ARG5 EDI
#define REG_SYSCALL_ARG6 EBP
#else
#define VALID_ARCH 0
#define SYSCALLS_QUANTITY 0
#define REG_SYSCALL_NUMBER  0
#define REG_SYSCALL_RETURN 0
#define REG_SYSCALL_ARG1 0
#define REG_SYSCALL_ARG2 0
#define REG_SYSCALL_ARG3 0
#define REG_SYSCALL_ARG4 0
#define REG_SYSCALL_ARG5 0
#define REG_SYSCALL_ARG6 0
#endif
#endif

// Structs

typedef struct system_call_information {
    char *system_call_name;
    char *system_call_args[ARGS_QUANTITY];
} system_call_information;

// Constants

const long int arguments[ARGS_QUANTITY] =
        {REG_SYSCALL_ARG1, REG_SYSCALL_ARG2, REG_SYSCALL_ARG3, REG_SYSCALL_ARG4, REG_SYSCALL_ARG5, REG_SYSCALL_ARG6};

#ifdef __x86_64__
const system_call_information syscalls_info[SYSCALLS_QUANTITY] = {
        {"sys_read", {"unsigned int fd", "char *buf", "size_t count", "", "", ""}},
        {"sys_write", {"unsigned int fd", "const char *buf", "size_t count", "", "", ""}},
        {"sys_open", {"const char *filename", "int flags", "int mode", "", "", ""}},
        {"sys_close", {"unsigned int fd", "", "", "", "", ""}},
        {"sys_stat", {"const char *filename", "struct stat *statbuf", "", "", "", ""}},
        {"sys_fstat", {"unsigned int fd", "struct stat *statbuf", "", "", "", ""}},
        {"sys_lstat", {"fconst char *filename", "struct stat *statbuf", "", "", "", ""}},
        {"sys_poll", {"struct poll_fd *ufds", "unsigned int nfds", "long timeout_msecs", "", "", ""}},
        {"sys_lseek", {"unsigned int fd", "off_t offset", "unsigned int origin", "", "", ""}},
        {"sys_mmap", {"unsigned long addr", "unsigned long len", "unsigned long prot", "unsigned long flags", "unsigned long fd", "unsigned long off"}},
        {"sys_mprotect", {"unsigned long start", "size_t len", "unsigned long prot", "", "", ""}},
        {"sys_munmap", {"unsigned long addr", "size_t len", "", "", "", ""}},
        {"sys_brk", {"unsigned long brk", "", "", "", "", ""}},
        {"sys_rt_sigaction", {"int sig", "const struct sigaction *act", "struct sigaction *oact", "size_t sigsetsize", "", ""}},
        {"sys_rt_sigprocmask", {"int how", "sigset_t *nset", "sigset_t *oset", "size_t sigsetsize", "", ""}},
        {"sys_rt_sigreturn", {"unsigned long __unused", "", "", "", "", ""}},
        {"sys_ioctl", {"unsigned int fd", "unsigned int cmd", "unsigned long arg", "", "", ""}},
        {"sys_pread64", {"unsigned long fd", "char *buf", "size_t count", "loff_t pos", "", ""}},
        {"sys_pwrite64", {"unsigned int fd", "const char *buf", "size_t count", "loff_t pos", "", ""}},
        {"sys_readv", {"unsigned long fd", "const struct iovec *vec", "unsigned long vlen", "", "", ""}},
        {"sys_writev", {"unsigned long fd", "const struct iovec *vec", "unsigned long vlen", "", "", ""}},
        {"sys_access", {"const char *filename", "int mode", "", "", "", ""}},
        {"sys_pipe", {"int *filedes", "", "", "", "", ""}},
        {"sys_select", {"int n", "fd_set *inp", "fd_set *outp", "fd_set*exp", "struct timeval *tvp", ""}},
        {"sys_sched_yield", {"", "", "", "", "", ""}},
        {"sys_mremap", {"unsigned long addr", "unsigned long old_len", "unsigned long new_len", "unsigned long flags", "unsigned long new_addr", ""}},
        {"sys_msync", {"unsigned long start", "size_t len", "int flags", "", "", ""}},
        {"sys_mincore", {"unsigned long start", "size_t len", "unsigned char *vec", "", "", ""}},
        {"sys_madvise", {"unsigned long start", "size_t len_in", "int behavior", "", "", ""}},
        {"sys_shmget", {"key_t key", "size_t size", "int shmflg", "", "", ""}},
        {"sys_shmat", {"int shmid", "char *shmaddr", "int shmflg", "", "", ""}},
        {"sys_shmctl", {"int shmid", "int cmd", "struct shmid_ds *buf", "", "", ""}},
        {"sys_dup", {"unsigned int fildes", "", "", "", "", ""}},
        {"sys_dup2", {"unsigned int oldfd", "unsigned int newfd", "", "", "", ""}},
        {"sys_pause", {"", "", "", "", "", ""}},
        {"sys_nanosleep", {"struct timespec *rqtp", "struct timespec *rmtp", "", "", "", ""}},
        {"sys_getitimer", {"int which", "struct itimerval *value", "", "", "", ""}},
        {"sys_alarm", {"unsigned int seconds", "", "", "", "", ""}},
        {"sys_setitimer", {"int which", "struct itimerval *value", "struct itimerval *ovalue", "", "", ""}},
        {"sys_getpid", {"", "", "", "", "", ""}},
        {"sys_sendfile", {"int out_fd", "int in_fd", "off_t *offset", "size_t count", "", ""}},
        {"sys_socket", {"int family", "int type", "int protocol", "", "", ""}},
        {"sys_connect", {"int fd", "struct sockaddr *uservaddr", "int addrlen", "", "", ""}},
        {"sys_accept", {"int fd", "struct sockaddr *upeer_sockaddr", "int *upeer_addrlen", "", "", ""}},
        {"sys_sendto", {"int fd", "void *buff", "size_t len", "unsigned flags", "struct sockaddr *addr", "int addr_len"}},
        {"sys_recvfrom", {"int fd", "void *ubuf", "size_t size", "unsigned flags", "struct sockaddr *addr", "int *addr_len"}},
        {"sys_sendmsg", {"int fd", "struct msghdr *msg", "unsigned flags", "", "", ""}},
        {"sys_recvmsg", {"int fd", "struct msghdr *msg", "unsigned int flags", "", "", ""}},
        {"sys_shutdown", {"int fd", "int how", "", "", "", ""}},
        {"sys_bind", {"int fd", "struct sokaddr *umyaddr", "int addrlen", "", "", ""}},
        {"sys_listen", {"int fd", "int backlog", "", "", "", ""}},
        {"sys_getsockname", {"int fd", "struct sockaddr *usockaddr", "int *usockaddr_len", "", "", ""}},
        {"sys_getpeername", {"int fd", "struct sockaddr *usockaddr", "int *usockaddr_len", "", "", ""}},
        {"sys_socketpair", {"int family", "int type", "int protocol", "int *usockvec", "", ""}},
        {"sys_setsockopt", {"int fd", "int level", "int optname", "char *optval", "int optlen", ""}},
        {"sys_getsockopt", {"int fd", "int level", "int optname", "char *optval", "int *optlen", ""}},
        {"sys_clone", {"unsigned long clone_flags", "unsigned long newsp", "void *parent_tid", "void *child_tid", "unsigned int tid", ""}},
        {"sys_fork", {"", "", "", "", "", ""}},
        {"sys_vfork", {"", "", "", "", "", ""}},
        {"sys_execve", {"const char *filename", "const char *const argv{}", "const char *const envp{}", "", "", ""}},
        {"sys_exit", {"int error_code", "", "", "", "", ""}},
        {"sys_wait4", {"pid_t upid", "int *stat_addr", "int options", "struct rusage *ru", "", ""}},
        {"sys_kill", {"pid_t pid", "int sig", "", "", "", ""}},
        {"sys_uname", {"struct old_utsname *name", "", "", "", "", ""}},
        {"sys_semget", {"key_t key", "int nsems", "int semflg", "", "", ""}},
        {"sys_semop", {"int semid", "struct sembuf *tsops", "unsigned nsops", "", "", ""}},
        {"sys_semctl", {"int semid", "int semnum", "int cmd", "union semun arg", "", ""}},
        {"sys_shmdt", {"char *shmaddr", "", "", "", "", ""}},
        {"sys_msgget", {"key_t key", "int msgflg", "", "", "", ""}},
        {"sys_msgsnd", {"int msqid", "struct msgbuf *msgp", "size_t msgsz", "int msgflg", "", ""}},
        {"sys_msgrcv", {"int msqid", "struct msgbuf *msgp", "size_t msgsz", "long msgtyp", "int msgflg", ""}},
        {"sys_msgctl", {"int msqid", "int cmd", "struct msqid_ds *buf", "", "", ""}},
        {"sys_fcntl", {"unsigned int fd", "unsigned int cmd", "unsigned long arg", "", "", ""}},
        {"sys_flock", {"unsigned int fd", "unsigned int cmd", "", "", "", ""}},
        {"sys_fsync", {"unsigned int fd", "", "", "", "", ""}},
        {"sys_fdatasync", {"unsigned int fd", "", "", "", "", ""}},
        {"sys_truncate", {"const char *path", "long length", "", "", "", ""}},
        {"sys_ftruncate", {"unsigned int fd", "unsigned long length", "", "", "", ""}},
        {"sys_getdents", {"unsigned int fd", "struct linux_dirent *dirent", "unsigned int count", "", "", ""}},
        {"sys_getcwd", {"char *buf", "unsigned long size", "", "", "", ""}},
        {"sys_chdir", {"const char *filename", "", "", "", "", ""}},
        {"sys_fchdir", {"unsigned int fd", "", "", "", "", ""}},
        {"sys_rename", {"const char *oldname", "const char *newname", "", "", "", ""}},
        {"sys_mkdir", {"const char *pathname", "int mode", "", "", "", ""}},
        {"sys_rmdir", {"const char *pathname", "", "", "", "", ""}},
        {"sys_creat", {"const char *pathname", "int mode", "", "", "", ""}},
        {"sys_link", {"const char *oldname", "const char *newname", "", "", "", ""}},
        {"sys_unlink", {"const char *pathname", "", "", "", "", ""}},
        {"sys_symlink", {"const char *oldname", "const char *newname", "", "", "", ""}},
        {"sys_readlink", {"const char *path", "char *buf", "int bufsiz", "", "", ""}},
        {"sys_chmod", {"const char *filename", "mode_t mode", "", "", "", ""}},
        {"sys_fchmod", {"unsigned int fd", "mode_t mode", "", "", "", ""}},
        {"sys_chown", {"const char *filename", "uid_t user", "gid_t group", "", "", ""}},
        {"sys_fchown", {"unsigned int fd", "uid_t user", "gid_t group", "", "", ""}},
        {"sys_lchown", {"const char *filename", "uid_t user", "gid_t group", "", "", ""}},
        {"sys_umask", {"int mask", "", "", "", "", ""}},
        {"sys_gettimeofday", {"struct timeval *tv", "struct timezone *tz", "", "", "", ""}},
        {"sys_getrlimit", {"unsigned int resource", "struct rlimit *rlim", "", "", "", ""}},
        {"sys_getrusage", {"int who", "struct rusage *ru", "", "", "", ""}},
        {"sys_sysinfo", {"struct sysinfo *info", "", "", "", "", ""}},
        {"sys_times", {"struct sysinfo *info", "", "", "", "", ""}},
        {"sys_ptrace", {"long request", "long pid", "unsigned long addr", "unsigned long data", "", ""}},
        {"sys_getuid", {"", "", "", "", "", ""}},
        {"sys_syslog", {"int type", "char *buf", "int len", "", "", ""}},
        {"sys_getgid", {"", "", "", "", "", ""}},
        {"sys_setuid", {"uid_t uid", "", "", "", "", ""}},
        {"sys_setgid", {"gid_t gid", "", "", "", "", ""}},
        {"sys_geteuid", {"", "", "", "", "", ""}},
        {"sys_getegid", {"", "", "", "", "", ""}},
        {"sys_setpgid", {"pid_t pid", "pid_t pgid", "", "", "", ""}},
        {"sys_getppid", {"", "", "", "", "", ""}},
        {"sys_getpgrp", {"", "", "", "", "", ""}},
        {"sys_setsid", {"", "", "", "", "", ""}},
        {"sys_setreuid", {"uid_t ruid", "uid_t euid", "", "", "", ""}},
        {"sys_setregid", {"gid_t rgid", "gid_t egid", "", "", "", ""}},
        {"sys_getgroups", {"int gidsetsize", "gid_t *grouplist", "", "", "", ""}},
        {"sys_setgroups", {"int gidsetsize", "gid_t *grouplist", "", "", "", ""}},
        {"sys_setresuid", {"uid_t *ruid", "uid_t *euid", "uid_t *suid", "", "", ""}},
        {"sys_getresuid", {"uid_t *ruid", "uid_t *euid", "uid_t *suid", "", "", ""}},
        {"sys_setresgid", {"gid_t rgid", "gid_t egid", "gid_t sgid", "", "", ""}},
        {"sys_getresgid", {"gid_t *rgid", "gid_t *egid", "gid_t *sgid", "", "", ""}},
        {"sys_getpgid", {"pid_t pid", "", "", "", "", ""}},
        {"sys_setfsuid", {"uid_t uid", "", "", "", "", ""}},
        {"sys_setfsgid", {"gid_t gid", "", "", "", "", ""}},
        {"sys_getsid", {"pid_t pid", "", "", "", "", ""}},
        {"sys_capget", {"cap_user_header_t header", "cap_user_data_t dataptr", "", "", "", ""}},
        {"sys_capset", {"cap_user_header_t header", "const cap_user_data_t data", "", "", "", ""}},
        {"sys_rt_sigpending", {"sigset_t *set", "size_t sigsetsize", "", "", "", ""}},
        {"sys_rt_sigtimedwait", {"const sigset_t *uthese", "siginfo_t *uinfo", "const struct timespec *uts", "size_t sigsetsize", "", ""}},
        {"sys_rt_sigqueueinfo", {"pid_t pid", "int sig", "siginfo_t *uinfo", "", "", ""}},
        {"sys_rt_sigsuspend", {"sigset_t *unewset", "size_t sigsetsize", "", "", "", ""}},
        {"sys_sigaltstack", {"const stack_t *uss", "stack_t *uoss", "", "", "", ""}},
        {"sys_utime", {"char *filename", "struct utimbuf *times", "", "", "", ""}},
        {"sys_mknod", {"const char *filename", "umode_t mode", "unsigned dev", "", "", ""}},
        {"sys_uselib", {"NOT IMPLEMENTED", "", "", "", "", ""}},
        {"sys_personality", {"unsigned int personality", "", "", "", "", ""}},
        {"sys_ustat", {"unsigned dev", "struct ustat *ubuf", "", "", "", ""}},
        {"sys_statfs", {"const char *pathname", "struct statfs *buf", "", "", "", ""}},
        {"sys_fstatfs", {"unsigned int fd", "struct statfs *buf", "", "", "", ""}},
        {"sys_sysfs", {"int option", "unsigned long arg1", "unsigned long arg2", "", "", ""}},
        {"sys_getpriority", {"int which", "int who", "", "", "", ""}},
        {"sys_setpriority", {"int which", "int who", "int niceval", "", "", ""}},
        {"sys_sched_setparam", {"pid_t pid", "struct sched_param *param", "", "", "", ""}},
        {"sys_sched_getparam", {"pid_t pid", "struct sched_param *param", "", "", "", ""}},
        {"sys_sched_setscheduler", {"pid_t pid", "int policy", "struct sched_param *param", "", "", ""}},
        {"sys_sched_getscheduler", {"pid_t pid", "", "", "", "", ""}},
        {"sys_sched_get_priority_max", {"int policy", "", "", "", "", ""}},
        {"sys_sched_get_priority_min", {"int policy", "", "", "", "", ""}},
        {"sys_sched_rr_get_interval", {"pid_t pid", "struct timespec *interval", "", "", "", ""}},
        {"sys_mlock", {"unsigned long start", "size_t len", "", "", "", ""}},
        {"sys_munlock", {"unsigned long start", "size_t len", "", "", "", ""}},
        {"sys_mlockall", {"int flags", "", "", "", "", ""}},
        {"sys_munlockall", {"", "", "", "", "", ""}},
        {"sys_vhangup", {"", "", "", "", "", ""}},
        {"sys_modify_ldt", {"int func", "void *ptr", "unsigned long bytecount", "", "", ""}},
        {"sys_pivot_root", {"const char *new_root", "const char *put_old", "", "", "", ""}},
        {"sys__sysctl", {"struct __sysctl_args *args", "", "", "", "", ""}},
        {"sys_prctl", {"int option", "unsigned long arg2", "unsigned long arg3", "unsigned long arg4", "", "unsigned long arg5"}},
        {"sys_arch_prctl", {"struct task_struct *task", "int code", "unsigned long *addr", "", "", ""}},
        {"sys_adjtimex", {"struct timex *txc_p", "", "", "", "", ""}},
        {"sys_setrlimit", {"unsigned int resource", "struct rlimit *rlim", "", "", "", ""}},
        {"sys_chroot", {"const char *filename", "", "", "", "", ""}},
        {"sys_sync", {"", "", "", "", "", ""}},
        {"sys_acct", {"const char *name", "", "", "", "", ""}},
        {"sys_settimeofday", {"struct timeval *tv", "struct timezone *tz", "", "", "", ""}},
        {"sys_mount", {"char *dev_name", "char *dir_name", "char *type", "unsigned long flags", "void *data", ""}},
        {"sys_umount2", {"const char *target", "int flags", "", "", "", ""}},
        {"sys_swapon", {"const char *specialfile", "int swap_flags", "", "", "", ""}},
        {"sys_swapoff", {"const char *specialfile", "", "", "", "", ""}},
        {"sys_reboot", {"int magic1", "int magic2", "unsigned int cmd", "void *arg", "", ""}},
        {"sys_sethostname", {"char *name", "int len", "", "", "", ""}},
        {"sys_setdomainname", {"char *name", "int len", "", "", "", ""}},
        {"sys_iopl", {"unsigned int level", "struct pt_regs *regs", "", "", "", ""}},
        {"sys_ioperm", {"unsigned long from", "unsigned long num", "int turn_on", "", "", ""}},
        {"sys_create_module", {"REMOVED IN Linux 2.6", "", "", "", "", ""}},
        {"sys_init_module", {"void *umod", "unsigned long len", "const char *uargs", "", "", ""}},
        {"sys_delete_module", {"const chat *name_user", "unsigned int flags", "", "", "", ""}},
        {"sys_get_kernel_syms", {"REMOVED IN Linux 2.6", "", "", "", "", ""}},
        {"sys_query_module", {"REMOVED IN Linux 2.6", "", "", "", "", ""}},
        {"sys_quotactl", {"unsigned int cmd", "const char *special", "qid_t id", "void *addr", "", ""}},
        {"sys_nfsservctl", {"NOT IMPLEMENTED", "", "", "", "", ""}},
        {"sys_getpmsg", {"NOT IMPLEMENTED", "", "", "", "", ""}},
        {"sys_putpmsg", {"NOT IMPLEMENTED", "", "", "", "", ""}},
        {"sys_afs_syscall", {"NOT IMPLEMENTED", "", "", "", "", ""}},
        {"sys_tuxcall", {"NOT IMPLEMENTED", "", "", "", "", ""}},
        {"sys_security", {"NOT IMPLEMENTED", "", "", "", "", ""}},
        {"sys_gettid", {"", "", "", "", "", ""}},
        {"sys_readahead", {"int fd", "loff_t offset", "size_t count", "", "", ""}},
        {"sys_setxattr", {"const char *pathname", "const char *name", "const void *value", "size_t size", "int flags", ""}},
        {"sys_lsetxattr", {"const char *pathname", "const char *name", "const void *value", "size_t size", "int flags", ""}},
        {"sys_fsetxattr", {"int fd", "const char *name", "const void *value", "size_t size", "int flags", ""}},
        {"sys_getxattr", {"const char *pathname", "const char *name", "void *value", "size_t size", "", ""}},
        {"sys_lgetxattr", {"const char *pathname", "const char *name", "void *value", "size_t size", "", ""}},
        {"sys_fgetxattr", {"int fd", "const har *name", "void *value", "size_t size", "", ""}},
        {"sys_listxattr", {"const char *pathname", "char *list", "size_t size", "", "", ""}},
        {"sys_llistxattr", {"const char *pathname", "char *list", "size_t size", "", "", ""}},
        {"sys_flistxattr", {"int fd", "char *list", "size_t size", "", "", ""}},
        {"sys_removexattr", {"const char *pathname", "const char *name", "", "", "", ""}},
        {"sys_lremovexattr", {"const char *pathname", "const char *name", "", "", "", ""}},
        {"sys_fremovexattr", {"int fd", "const char *name", "", "", "", ""}},
        {"sys_tkill", {"pid_t pid", "ing sig", "", "", "", ""}},
        {"sys_time", {"time_t *tloc", "", "", "", "", ""}},
        {"sys_futex", {"u32 *uaddr", "int op", "u32 val", "struct timespec *utime", "u32 *uaddr2", "u32 val3"}},
        {"sys_sched_setaffinity", {"pid_t pid", "unsigned int len", "unsigned long *user_mask_ptr", "", "", ""}},
        {"sys_sched_getaffinity", {"pid_t pid", "unsigned int len", "unsigned long *user_mask_ptr", "", "", ""}},
        {"sys_set_thread_area", {"NOT IMPLEMENTED. Use arch_prctl", "", "", "", "", ""}},
        {"sys_io_setup", {"unsigned nr_events", "aio_context_t *ctxp", "", "", "", ""}},
        {"sys_io_destroy", {"aio_context_t ctx", "", "", "", "", ""}},
        {"sys_io_getevents", {"aio_context_t ctx_id", "long min_nr", "long nr", "struct io_event *events", "", ""}},
        {"sys_io_submit", {"aio_context_t ctx_id", "long nr", "struct iocb **iocbpp", "", "", ""}},
        {"sys_io_cancel", {"aio_context_t ctx_id", "struct iocb *iocb", "struct io_event *result", "", "", ""}},
        {"sys_get_thread_area", {"NOT IMPLEMENTED. Use arch_prctl", "", "", "", "", ""}},
        {"sys_lookup_dcookie", {"u64 cookie64", "long buf", "long len", "", "", ""}},
        {"sys_epoll_create", {"int size", "", "", "", "", ""}},
        {"sys_epoll_ctl_old", {"NOT IMPLEMENTED", "", "", "", "", ""}},
        {"sys_epoll_wait_old", {"NOT IMPLEMENTED", "", "", "", "", ""}},
        {"sys_remap_file_pages", {"unsigned long start", "unsigned long size", "unsigned long prot", "unsigned long pgoff", "unsigned long flags", ""}},
        {"sys_getdents64", {"unsigned int fd", "struct linux_dirent64 *dirent", "unsigned int count", "", "", ""}},
        {"sys_set_tid_address", {"int *tidptr", "", "", "", "", ""}},
        {"sys_restart_syscall", {"", "", "", "", "", ""}},
        {"sys_semtimedop", {"int semid", "struct sembuf *tsops", "unsigned nsops", "const struct timespec *timeout", "", ""}},
        {"sys_fadvise64", {"int fd", "loff_t offset", "size_t len", "int advice", "", ""}},
        {"sys_timer_create", {"const clockid_t which_clock", "struct sigevent *timer_event_spec", "timer_t *created_timer_id", "", "", ""}},
        {"sys_timer_settime", {"timer_t timer_id", "int flags", "const struct itimerspec *new_setting", "struct itimerspec *old_setting", "", ""}},
        {"sys_timer_gettime", {"timer_t timer_id", "struct itimerspec *setting", "", "", "", ""}},
        {"sys_timer_getoverrun", {"timer_t timer_id", "", "", "", "", ""}},
        {"sys_timer_delete", {"timer_t timer_id", "", "", "", "", ""}},
        {"sys_clock_settime", {"const clockid_t which_clock", "const struct timespec *tp", "", "", "", ""}},
        {"sys_clock_gettime", {"const clockid_t which_clock", "struct timespec *tp", "", "", "", ""}},
        {"sys_clock_getres", {"const clockid_t which_clock", "struct timespec *tp", "", "", "", ""}},
        {"sys_clock_nanosleep", {"const clockid_t which_clock", "int flags", "const struct timespec *rqtp", "struct timespec *rmtp", "", ""}},
        {"sys_exit_group", {"int error_code", "", "", "", "", ""}},
        {"sys_epoll_wait", {"int epfd", "struct epoll_event *events", "int maxevents", "int timeout", "", ""}},
        {"sys_epoll_ctl", {"int epfd", "int op", "int fd", "struct epoll_event *event", "", ""}},
        {"sys_tgkill", {"pid_t tgid", "pid_t pid", "int sig", "", "", ""}},
        {"sys_utimes", {"char *filename", "struct timeval *utimes", "", "", "", ""}},
        {"sys_vserver", {"NOT IMPLEMENTED", "", "", "", "", ""}},
        {"sys_mbind", {"unsigned long start", "unsigned long len", "unsigned long mode", "unsigned long *nmask", "unsigned long maxnode", "unsigned flags"}},
        {"sys_set_mempolicy", {"int mode", "unsigned long *nmask", "unsigned long maxnode", "", "", ""}},
        {"sys_get_mempolicy", {"int *policy", "unsigned long *nmask", "unsigned long maxnode", "unsigned long addr", "unsigned long flags", ""}},
        {"sys_mq_open", {"const char *u_name", "int oflag", "mode_t mode", "struct mq_attr *u_attr", "", ""}},
        {"sys_mq_unlink", {"const char *u_name", "", "", "", "", ""}},
        {"sys_mq_timedsend", {"mqd_t mqdes", "const char *u_msg_ptr", "size_t msg_len", "unsigned int msg_prio", "const stuct timespec *u_abs_timeout", ""}},
        {"sys_mq_timedreceive", {"mqd_t mqdes", "char *u_msg_ptr", "size_t msg_len", "unsigned int *u_msg_prio", "const struct timespec *u_abs_timeout", ""}},
        {"sys_mq_notify", {"mqd_t mqdes", "const struct sigevent *u_notification", "", "", "", ""}},
        {"sys_mq_getsetattr", {"mqd_t mqdes", "const struct mq_attr *u_mqstat", "struct mq_attr *u_omqstat", "", "", ""}},
        {"sys_kexec_load", {"unsigned long entry", "unsigned long nr_segments", "struct kexec_segment *segments", "unsigned long flags", "", ""}},
        {"sys_waitid", {"int which", "pid_t upid", "struct siginfo *infop", "int options", "struct rusage *ru", ""}},
        {"sys_add_key", {"const char *_type", "const char *_description", "const void *_payload", "size_t plen", "", ""}},
        {"sys_request_key", {"const char *_type", "const char *_description", "const char *_callout_info", "key_serial_t destringid", "", ""}},
        {"sys_keyctl", {"int option", "unsigned long arg2", "unsigned long arg3", "unsigned long arg4", "unsigned long arg5", ""}},
        {"sys_ioprio_set", {"int which", "int who", "int ioprio", "", "", ""}},
        {"sys_ioprio_get", {"int which", "int who", "", "", "", ""}},
        {"sys_inotify_init", {"", "", "", "", "", ""}},
        {"sys_inotify_add_watch", {"int fd", "const char *pathname", "u32 mask", "", "", ""}},
        {"sys_inotify_rm_watch", {"int fd", "__s32 wd", "", "", "", ""}},
        {"sys_migrate_pages", {"pid_t pid", "unsigned long maxnode", "const unsigned long *old_nodes", "const unsigned long *new_nodes", "", ""}},
        {"sys_openat", {"int dfd", "const char *filename", "int flags", "int mode", "", ""}},
        {"sys_mkdirat", {"int dfd", "const char *pathname", "int mode", "", "", ""}},
        {"sys_mknodat", {"int dfd", "const char *filename", "int mode", "unsigned dev", "", ""}},
        {"sys_fchownat", {"int dfd", "const char *filename", "uid_t user", "gid_t group", "int flag", ""}},
        {"sys_futimesat", {"int dfd", "const char *filename", "struct timeval *utimes", "", "", ""}},
        {"sys_newfstatat", {"int dfd", "const char *filename", "struct stat *statbuf", "int flag", "", ""}},
        {"sys_unlinkat", {"int dfd", "const char *pathname", "int flag", "", "", ""}},
        {"sys_renameat", {"int oldfd", "const char *oldname", "int newfd", "const char *newname", "", ""}},
        {"sys_linkat", {"int oldfd", "const char *oldname", "int newfd", "const char *newname", "int flags", ""}},
        {"sys_symlinkat", {"const char *oldname", "int newfd", "const char *newname", "", "", ""}},
        {"sys_readlinkat", {"int dfd", "const char *pathname", "char *buf", "int bufsiz", "", ""}},
        {"sys_fchmodat", {"int dfd", "const char *filename", "mode_t mode", "", "", ""}},
        {"sys_faccessat", {"int dfd", "const char *filename", "int mode", "", "", ""}},
        {"sys_pselect6", {"int n", "fd_set *inp", "fd_set *outp", "fd_set *exp", "struct timespec *tsp", "void *sig"}},
        {"sys_ppoll", {"struct pollfd *ufds", "unsigned int nfds", "struct timespec *tsp", "const sigset_t *sigmask", "size_t sigsetsize", ""}},
        {"sys_unshare", {"unsigned long unshare_flags", "", "", "", "", ""}},
        {"sys_set_robust_list", {"struct robust_list_head *head", "size_t len", "", "", "", ""}},
        {"sys_get_robust_list", {"int pid", "struct robust_list_head **head_ptr", "size_t *len_ptr", "", "", ""}},
        {"sys_splice", {"int fd_in", "loff_t *off_in", "int fd_out", "loff_t *off_out", "size_t len", "unsigned int flags"}},
        {"sys_tee", {"int fdin", "int fdout", "size_t len", "unsigned int flags", "", ""}},
        {"sys_sync_file_range", {"long fd", "loff_t offset", "loff_t bytes", "long flags", "", ""}},
        {"sys_vmsplice", {"int fd", "const struct iovec *iov", "unsigned long nr_segs", "unsigned int flags", "", ""}},
        {"sys_move_pages", {"pid_t pid", "unsigned long nr_pages", "const void **pages", "const int *nodes", "int *status", "int flags"}},
        {"sys_utimensat", {"int dfd", "const char *filename", "struct timespec *utimes", "int flags", "", ""}},
        {"sys_epoll_pwait", {"int epfd", "struct epoll_event *events", "int maxevents", "int timeout", "const sigset_t *sigmask", "size_t sigsetsize"}},
        {"sys_signalfd", {"int ufd", "sigset_t *user_mask", "size_t sizemask", "", "", ""}},
        {"sys_timerfd_create", {"int clockid", "int flags", "", "", "", ""}},
        {"sys_eventfd", {"unsigned int count", "", "", "", "", ""}},
        {"sys_fallocate", {"long fd", "long mode", "loff_t offset", "loff_t len", "", ""}},
        {"sys_timerfd_settime", {"int ufd", "int flags", "const struct itimerspec *utmr", "struct itimerspec *otmr", "", ""}},
        {"sys_timerfd_gettime", {"int ufd", "struct itimerspec *otmr", "", "", "", ""}},
        {"sys_accept4", {"int fd", "struct sockaddr *upeer_sockaddr", "int *upeer_addrlen", "int flags", "", ""}},
        {"sys_signalfd4", {"int ufd", "sigset_t *user_mask", "size_t sizemask", "int flags", "", ""}},
        {"sys_eventfd2", {"unsigned int count", "int flags", "", "", "", ""}},
        {"sys_epoll_create1", {"int flags", "", "", "", "", ""}},
        {"sys_dup3", {"unsigned int oldfd", "unsigned int newfd", "int flags", "", "", ""}},
        {"sys_pipe2", {"int *filedes", "int flags", "", "", "", ""}},
        {"sys_inotify_init1", {"int flags", "", "", "", "", ""}},
        {"sys_preadv", {"unsigned long fd", "const struct iovec *vec", "unsigned long vlen", "unsigned long pos_l", "unsigned long pos_h", ""}},
        {"sys_pwritev", {"unsigned long fd", "const struct iovec *vec", "unsigned long vlen", "unsigned long pos_l", "unsigned long pos_h", ""}},
        {"sys_rt_tgsigqueueinfo", {"pid_t tgid", "pid_t pid", "int sig", "siginfo_t *uinfo", "", ""}},
        {"sys_perf_event_open", {"struct perf_event_attr *attr_uptr", "pid_t pid", "int cpu", "int group_fd", "unsigned long flags", ""}},
        {"sys_recvmmsg", {"int fd", "struct msghdr *mmsg", "unsigned int vlen", "unsigned int flags", "struct timespec *timeout", ""}},
        {"sys_fanotify_init", {"unsigned int flags", "unsigned int event_f_flags", "", "", "", ""}},
        {"sys_fanotify_mark", {"long fanotify_fd", "long flags", "__u64 mask", "long dfd", "long pathname", ""}},
        {"sys_prlimit64", {"pid_t pid", "unsigned int resource", "const struct rlimit64 *new_rlim", "struct rlimit64 *old_rlim", "", ""}},
        {"sys_name_to_handle_at", {"int dfd", "const char *name", "struct file_handle *handle", "int *mnt_id", "int flag", ""}},
        {"sys_open_by_handle_at", {"int dfd", "const char *name", "struct file_handle *handle", "int *mnt_id", "int flags", ""}},
        {"sys_clock_adjtime", {"clockid_t which_clock", "struct timex *tx", "", "", "", ""}},
        {"sys_syncfs", {"int fd", "", "", "", "", ""}},
        {"sys_sendmmsg", {"int fd", "struct mmsghdr *mmsg", "unsigned int vlen", "unsigned int flags", "", ""}},
        {"sys_setns", {"int fd", "int nstype", "", "", "", ""}},
        {"sys_getcpu", {"unsigned *cpup", "unsigned *nodep", "struct getcpu_cache *unused", "", "", ""}},
        {"sys_process_vm_readv", {"pid_t pid", "const struct iovec *lvec", "unsigned long liovcnt", "const struct iovec *rvec", "unsigned long riovcnt", "unsigned long flags"}},
        {"sys_process_vm_writev", {"pid_t pid", "const struct iovec *lvec", "unsigned long liovcnt", "const struct iovcc *rvec", "unsigned long riovcnt", "unsigned long flags"}},
        {"sys_kcmp", {"pid_t pid1", "pid_t pid2", "int type", "unsigned long idx1", "unsigned long idx2", ""}},
        {"sys_finit_module", {"int fd", "const char __user *uargs", "int flags", "", "", ""}},
        {"sys_sched_setattr", {"pid_t pid", "struct sched_attr __user *attr", "unsigned int flags", "", "", ""}},
        {"sys_sched_getattr", {"pid_t pid", "struct sched_attr __user *attr", "unsigned int size", "unsigned int flags", "", ""}},
        {"sys_renameat2", {"int olddfd", "const char __user *oldname", "int newdfd", "const char __user *newname", "unsigned int flags", ""}},
        {"sys_seccomp", {"unsigned int op", "unsigned int flags", "const char __user *uargs", "", "", ""}},
        {"sys_getrandom", {"char __user *buf", "size_t count", "unsigned int flags", "", "", ""}},
        {"sys_memfd_create", {"const char __user *uname_ptr", "unsigned int flags", "", "", "", ""}},
        {"sys_kexec_file_load", {"int kernel_fd", "int initrd_fd", "unsigned long cmdline_len", "const char __user *cmdline_ptr", "unsigned long flags", ""}},
        {"sys_bpf", {"int cmd", "union bpf_attr *attr", "unsigned int size", "", "", ""}},
        {"stub_execveat", {"int dfd", "const char __user *filename", "const char __user *const __user *argv", "const char __user *const __user *envp", "int flags", ""}},
        {"userfaultfd", {"int flags", "", "", "", "", ""}},
        {"membarrier", {"int cmd", "int flags", "", "", "", ""}},
        {"mlock2", {"unsigned long start", "size_t len", "int flags", "", "", ""}},
        {"copy_file_range", {"int fd_in", "loff_t __user *off_in", "int fd_out", "loff_t __user * off_out", "size_t len", "unsigned int flags"}},
        {"preadv2", {"unsigned long fd", "const struct iovec __user *vec", "unsigned long vlen", "unsigned long pos_l", "unsigned long pos_h", "int flags"}},
        {"pwritev2", {"unsigned long fd", "const struct iovec __user *vec", "unsigned long vlen", "unsigned long pos_l", "unsigned long pos_h", "int flags"}},
        {"pkey_mprotect", {"", "", "", "", "", ""}},
        {"pkey_alloc", {"", "", "", "", "", ""}},
        {"pkey_free", {"", "", "", "", "", ""}},
        {"statx", {"", "", "", "", "", ""}},
        {"io_pgetevents", {"", "", "", "", "", ""}},
        {"rseq", {"", "", "", "", "", ""}},
        {"pkey_mprotect", {"", "", "", "", "", ""}}
};
#else
#ifdef __i386__
const system_call_information syscalls_info[SYSCALLS_QUANTITY] = {
        {"restart_syscall", {"", "", "", "", "", ""}},
        {"exit", {"int error_code", "", "", "", "", ""}},
        {"fork", {"", "", "", "", "", ""}},
        {"read", {"unsigned int fd", "char *buf", "size_t count", "", "", ""}},
        {"write", {"unsigned int fd", "const char *buf", "size_t count", "", "", ""}},
        {"open", {"const char *filename", "int flags", "umode_t mode", "", "", ""}},
        {"close", {"unsigned int fd", "", "", "", "", ""}},
        {"waitpid", {"pid_t pid", "int *stat_addr", "int options", "", "", ""}},
        {"creat", {"const char *pathname", "umode_t mode", "", "", "", ""}},
        {"link", {"const char *oldname", "const char *newname", "", "", "", ""}},
        {"unlink", {"const char *pathname", "", "", "", "", ""}},
        {"execve", {"const char *filename", "const char *const *argv", "const char *const *envp", "", "", ""}},
        {"chdir", {"const char *filename", "", "", "", "", ""}},
        {"time", {"time_t *tloc", "", "", "", "", ""}},
        {"mknod", {"const char *filename", "umode_t mode", "unsigned dev", "", "", ""}},
        {"chmod", {"const char *filename", "umode_t mode", "", "", "", ""}},
        {"lchown", {"const char *filename", "uid_t user", "gid_t group", "", "", ""}},
        {"break", {"", "", "", "", "", ""}},
        {"oldstat", {"", "", "", "", "", ""}},
        {"lseek", {"unsigned int fd", "off_t offset", "unsigned int whence", "", "", ""}},
        {"getpid", {"", "", "", "", "", ""}},
        {"mount", {"char *dev_name", "char *dir_name", "char *type", "unsigned long flags", "void *data", ""}},
        {"umount", {"char *name", "int flags", "", "", "", ""}},
        {"setuid", {"uid_t uid", "", "", "", "", ""}},
        {"getuid", {"", "", "", "", "", ""}},
        {"stime", {"time_t *tptr", "", "", "", "", ""}},
        {"ptrace", {"long request", "long pid", "unsigned long addr", "unsigned long data", "", ""}},
        {"alarm", {"unsigned int seconds", "", "", "", "", ""}},
        {"oldfstat", {"", "", "", "", "", ""}},
        {"pause", {"", "", "", "", "", ""}},
        {"utime", {"char *filename", "struct utimbuf *times", "", "", "", ""}},
        {"stty", {"", "", "", "", "", ""}},
        {"gtty", {"", "", "", "", "", ""}},
        {"access", {"const char *filename", "int mode", "", "", "", ""}},
        {"nice", {"int increment", "", "", "", "", ""}},
        {"ftime", {"", "", "", "", "", ""}},
        {"sync", {"", "", "", "", "", ""}},
        {"kill", {"pid_t pid", "int sig", "", "", "", ""}},
        {"rename", {"const char *oldname", "const char *newname", "", "", "", ""}},
        {"mkdir", {"const char *pathname", "umode_t mode", "", "", "", ""}},
        {"rmdir", {"const char *pathname", "", "", "", "", ""}},
        {"dup", {"unsigned int fildes", "", "", "", "", ""}},
        {"pipe", {"int *fildes", "", "", "", "", ""}},
        {"times", {"struct tms *tbuf", "", "", "", "", ""}},
        {"prof", {"", "", "", "", "", ""}},
        {"brk", {"unsigned long brk", "", "", "", "", ""}},
        {"setgid", {"gid_t gid", "", "", "", "", ""}},
        {"getgid", {"", "", "", "", "", ""}},
        {"signal", {"int sig", "__sighandler_t handler", "", "", "", ""}},
        {"geteuid", {"", "", "", "", "", ""}},
        {"getegid", {"", "", "", "", "", ""}},
        {"acct", {"const char *name", "", "", "", "", ""}},
        {"umount2", {"", "", "", "", "", ""}},
        {"lock", {"", "", "", "", "", ""}},
        {"ioctl", {"unsigned int fd", "unsigned int cmd", "unsigned long arg", "", "", ""}},
        {"fcntl", {"unsigned int fd", "unsigned int cmd", "unsigned long arg", "", "", ""}},
        {"mpx", {"", "", "", "", "", ""}},
        {"setpgid", {"pid_t pid", "pid_t pgid", "", "", "", ""}},
        {"ulimit", {"", "", "", "", "", ""}},
        {"oldolduname", {"", "", "", "", "", ""}},
        {"umask", {"int mask", "", "", "", "", ""}},
        {"chroot", {"const char *filename", "", "", "", "", ""}},
        {"ustat", {"unsigned dev", "struct ustat *ubuf", "", "", "", ""}},
        {"dup2", {"unsigned int oldfd", "unsigned int newfd", "", "", "", ""}},
        {"getppid", {"", "", "", "", "", ""}},
        {"getpgrp", {"", "", "", "", "", ""}},
        {"setsid", {"", "", "", "", "", ""}},
        {"sigaction", {"int", "const struct old_sigaction *", "struct old_sigaction *", "", "", ""}},
        {"sgetmask", {"", "", "", "", "", ""}},
        {"ssetmask", {"int newmask", "", "", "", "", ""}},
        {"setreuid", {"uid_t ruid", "uid_t euid", "", "", "", ""}},
        {"setregid", {"gid_t rgid", "gid_t egid", "", "", "", ""}},
        {"sigsuspend", {"int unused1", "int unused2", "old_sigset_t mask", "", "", ""}},
        {"sigpending", {"old_sigset_t *uset", "", "", "", "", ""}},
        {"sethostname", {"char *name", "int len", "", "", "", ""}},
        {"setrlimit", {"unsigned int resource", "struct rlimit *rlim", "", "", "", ""}},
        {"getrlimit", {"unsigned int resource", "struct rlimit *rlim", "", "", "", ""}},
        {"getrusage", {"int who", "struct rusage *ru", "", "", "", ""}},
        {"gettimeofday", {"struct timeval *tv", "struct timezone *tz", "", "", "", ""}},
        {"settimeofday", {"struct timeval *tv", "struct timezone *tz", "", "", "", ""}},
        {"getgroups", {"int gidsetsize", "gid_t *grouplist", "", "", "", ""}},
        {"setgroups", {"int gidsetsize", "gid_t *grouplist", "", "", "", ""}},
        {"select", {"int n", "fd_set *inp", "fd_set *outp", "fd_set *exp", "struct timeval *tvp", ""}},
        {"symlink", {"const char *old", "const char *new", "", "", "", ""}},
        {"oldlstat", {"", "", "", "", "", ""}},
        {"readlink", {"const char *path", "char *buf", "int bufsiz", "", "", ""}},
        {"uselib", {"const char *library", "", "", "", "", ""}},
        {"swapon", {"const char *specialfile", "int swap_flags", "", "", "", ""}},
        {"reboot", {"int magic1", "int magic2", "unsigned int cmd", "void *arg", "", ""}},
        {"readdir", {"", "", "", "", "", ""}},
        {"mmap", {"", "", "", "", "", ""}},
        {"munmap", {"unsigned long addr", "size_t len", "", "", "", ""}},
        {"truncate", {"const char *path", "long length", "", "", "", ""}},
        {"ftruncate", {"unsigned int fd", "unsigned long length", "", "", "", ""}},
        {"fchmod", {"unsigned int fd", "umode_t mode", "", "", "", ""}},
        {"fchown", {"unsigned int fd", "uid_t user", "gid_t group", "", "", ""}},
        {"getpriority", {"int which", "int who", "", "", "", ""}},
        {"setpriority", {"int which", "int who", "int niceval", "", "", ""}},
        {"profil", {"", "", "", "", "", ""}},
        {"statfs", {"const char * path", "struct statfs *buf", "", "", "", ""}},
        {"fstatfs", {"unsigned int fd", "struct statfs *buf", "", "", "", ""}},
        {"ioperm", {"unsigned long from", "unsigned long num", "int on", "", "", ""}},
        {"socketcall", {"int call", "unsigned long *args", "", "", "", ""}},
        {"syslog", {"int type", "char *buf", "int len", "", "", ""}},
        {"setitimer", {"int which", "struct itimerval *value", "struct itimerval *ovalue", "", "", ""}},
        {"getitimer", {"int which", "struct itimerval *value", "", "", "", ""}},
        {"stat", {"const char *filename", "struct __old_kernel_stat *statbuf", "", "", "", ""}},
        {"lstat", {"const char *filename", "struct __old_kernel_stat *statbuf", "", "", "", ""}},
        {"fstat", {"unsigned int fd", "struct __old_kernel_stat *statbuf", "", "", "", ""}},
        {"olduname", {"struct oldold_utsname *", "", "", "", "", ""}},
        {"iopl", {"", "", "", "", "", ""}},
        {"vhangup", {"", "", "", "", "", ""}},
        {"idle", {"", "", "", "", "", ""}},
        {"vm86old", {"", "", "", "", "", ""}},
        {"wait4", {"pid_t pid", "int *stat_addr", "int options", "struct rusage *ru", "", ""}},
        {"swapoff", {"const char *specialfile", "", "", "", "", ""}},
        {"sysinfo", {"struct sysinfo *info", "", "", "", "", ""}},
        {"ipc", {"unsigned int call", "int first", "unsigned long second", "unsigned long third", "void *ptr", "long fifth"}},
        {"fsync", {"unsigned int fd", "", "", "", "", ""}},
        {"sigreturn", {"", "", "", "", "", ""}},
        {"clone", {"unsigned long", "unsigned long", "int *", "int *", "unsigned long", ""}},
        {"setdomainname", {"char *name", "int len", "", "", "", ""}},
        {"uname", {"struct old_utsname *", "", "", "", "", ""}},
        {"modify_ldt", {"", "", "", "", "", ""}},
        {"adjtimex", {"struct timex *txc_p", "", "", "", "", ""}},
        {"mprotect", {"unsigned long start", "size_t len", "unsigned long prot", "", "", ""}},
        {"sigprocmask", {"int how", "old_sigset_t *set", "old_sigset_t *oset", "", "", ""}},
        {"create_module", {"", "", "", "", "", ""}},
        {"init_module", {"void *umod", "unsigned long len", "const char *uargs", "", "", ""}},
        {"delete_module", {"const char *name_user", "unsigned int flags", "", "", "", ""}},
        {"get_kernel_syms", {"", "", "", "", "", ""}},
        {"quotactl", {"unsigned int cmd", "const char *special", "qid_t id", "void *addr", "", ""}},
        {"getpgid", {"pid_t pid", "", "", "", "", ""}},
        {"fchdir", {"unsigned int fd", "", "", "", "", ""}},
        {"bdflush", {"int func", "long data", "", "", "", ""}},
        {"sysfs", {"int option", "unsigned long arg1", "unsigned long arg2", "", "", ""}},
        {"personality", {"unsigned int personality", "", "", "", "", ""}},
        {"afs_syscall", {"", "", "", "", "", ""}},
        {"setfsuid", {"uid_t uid", "", "", "", "", ""}},
        {"setfsgid", {"gid_t gid", "", "", "", "", ""}},
        {"_llseek", {"", "", "", "", "", ""}},
        {"getdents", {"unsigned int fd", "struct linux_dirent *dirent", "unsigned int count", "", "", ""}},
        {"_newselect", {"", "", "", "", "", ""}},
        {"flock", {"unsigned int fd", "unsigned int cmd", "", "", "", ""}},
        {"msync", {"unsigned long start", "size_t len", "int flags", "", "", ""}},
        {"readv", {"unsigned long fd", "const struct iovec *vec", "unsigned long vlen", "", "", ""}},
        {"writev", {"unsigned long fd", "const struct iovec *vec", "unsigned long vlen", "", "", ""}},
        {"getsid", {"pid_t pid", "", "", "", "", ""}},
        {"fdatasync", {"unsigned int fd", "", "", "", "", ""}},
        {"_sysctl", {"", "", "", "", "", ""}},
        {"mlock", {"unsigned long start", "size_t len", "", "", "", ""}},
        {"munlock", {"unsigned long start", "size_t len", "", "", "", ""}},
        {"mlockall", {"int flags", "", "", "", "", ""}},
        {"munlockall", {"", "", "", "", "", ""}},
        {"sched_setparam", {"pid_t pid", "struct sched_param *param", "", "", "", ""}},
        {"sched_getparam", {"pid_t pid", "struct sched_param *param", "", "", "", ""}},
        {"sched_setscheduler", {"pid_t pid", "int policy", "struct sched_param *param", "", "", ""}},
        {"sched_getscheduler", {"pid_t pid", "", "", "", "", ""}},
        {"sched_yield", {"", "", "", "", "", ""}},
        {"sched_get_priority_max", {"int policy", "", "", "", "", ""}},
        {"sched_get_priority_min", {"int policy", "", "", "", "", ""}},
        {"sched_rr_get_interval", {"pid_t pid", "struct timespec *interval", "", "", "", ""}},
        {"nanosleep", {"struct __kernel_timespec *rqtp", "struct __kernel_timespec *rmtp", "", "", "", ""}},
        {"mremap", {"unsigned long addr", "unsigned long old_len", "unsigned long new_len", "unsigned long flags", "unsigned long new_addr", ""}},
        {"setresuid", {"uid_t ruid", "uid_t euid", "uid_t suid", "", "", ""}},
        {"getresuid", {"uid_t *ruid", "uid_t *euid", "uid_t *suid", "", "", ""}},
        {"vm86", {"", "", "", "", "", ""}},
        {"query_module", {"", "", "", "", "", ""}},
        {"poll", {"struct pollfd *ufds", "unsigned int nfds", "int timeout", "", "", ""}},
        {"nfsservctl", {"", "", "", "", "", ""}},
        {"setresgid", {"gid_t rgid", "gid_t egid", "gid_t sgid", "", "", ""}},
        {"getresgid", {"gid_t *rgid", "gid_t *egid", "gid_t *sgid", "", "", ""}},
        {"prctl", {"int option", "unsigned long arg2", "unsigned long arg3", "unsigned long arg4", "unsigned long arg5", ""}},
        {"rt_sigreturn", {"", "", "", "", "", ""}},
        {"rt_sigaction", {"int", "const struct sigaction *", "struct sigaction *", "size_t", "", ""}},
        {"rt_sigprocmask", {"int how", "sigset_t *set", "sigset_t *oset", "size_t sigsetsize", "", ""}},
        {"rt_sigpending", {"sigset_t *set", "size_t sigsetsize", "", "", "", ""}},
        {"rt_sigtimedwait", {"const sigset_t *uthese", "siginfo_t *uinfo", "const struct timespec *uts", "size_t sigsetsize", "", ""}},
        {"rt_sigqueueinfo", {"pid_t pid", "int sig", "siginfo_t *uinfo", "", "", ""}},
        {"rt_sigsuspend", {"sigset_t *unewset", "size_t sigsetsize", "", "", "", ""}},
        {"pread64", {"unsigned int fd", "char *buf", "size_t count", "loff_t pos", "", ""}},
        {"pwrite64", {"unsigned int fd", "const char *buf", "size_t count", "loff_t pos", "", ""}},
        {"chown", {"const char *filename", "uid_t user", "gid_t group", "", "", ""}},
        {"getcwd", {"char *buf", "unsigned long size", "", "", "", ""}},
        {"capget", {"cap_user_header_t header", "cap_user_data_t dataptr", "", "", "", ""}},
        {"capset", {"cap_user_header_t header", "const cap_user_data_t data", "", "", "", ""}},
        {"sigaltstack", {"const struct sigaltstack *uss", "struct sigaltstack *uoss", "", "", "", ""}},
        {"sendfile", {"int out_fd", "int in_fd", "off_t *offset", "size_t count", "", ""}},
        {"getpmsg", {"", "", "", "", "", ""}},
        {"putpmsg", {"", "", "", "", "", ""}},
        {"vfork", {"", "", "", "", "", ""}},
        {"ugetrlimit", {"", "", "", "", "", ""}},
        {"mmap2", {"", "", "", "", "", ""}},
        {"truncate64", {"const char *path", "loff_t length", "", "", "", ""}},
        {"ftruncate64", {"unsigned int fd", "loff_t length", "", "", "", ""}},
        {"stat64", {"const char *filename", "struct stat64 *statbuf", "", "", "", ""}},
        {"lstat64", {"const char *filename", "struct stat64 *statbuf", "", "", "", ""}},
        {"fstat64", {"unsigned long fd", "struct stat64 *statbuf", "", "", "", ""}},
        {"lchown32", {"", "", "", "", "", ""}},
        {"getuid32", {"", "", "", "", "", ""}},
        {"getgid32", {"", "", "", "", "", ""}},
        {"geteuid32", {"", "", "", "", "", ""}},
        {"getegid32", {"", "", "", "", "", ""}},
        {"setreuid32", {"", "", "", "", "", ""}},
        {"setregid32", {"", "", "", "", "", ""}},
        {"getgroups32", {"", "", "", "", "", ""}},
        {"setgroups32", {"", "", "", "", "", ""}},
        {"fchown32", {"", "", "", "", "", ""}},
        {"setresuid32", {"", "", "", "", "", ""}},
        {"getresuid32", {"", "", "", "", "", ""}},
        {"setresgid32", {"", "", "", "", "", ""}},
        {"getresgid32", {"", "", "", "", "", ""}},
        {"chown32", {"", "", "", "", "", ""}},
        {"setuid32", {"", "", "", "", "", ""}},
        {"setgid32", {"", "", "", "", "", ""}},
        {"setfsuid32", {"", "", "", "", "", ""}},
        {"setfsgid32", {"", "", "", "", "", ""}},
        {"pivot_root", {"const char *new_root", "const char *put_old", "", "", "", ""}},
        {"mincore", {"unsigned long start", "size_t len", "unsigned char * vec", "", "", ""}},
        {"madvise", {"unsigned long start", "size_t len", "int behavior", "", "", ""}},
        {"getdents64", {"unsigned int fd", "struct linux_dirent64 *dirent", "unsigned int count", "", "", ""}},
        {"fcntl64", {"unsigned int fd", "unsigned int cmd", "unsigned long arg", "", "", ""}},
        {"not implemented", {"", "", "", "", "", ""}},
        {"not implemented", {"", "", "", "", "", ""}},
        {"gettid", {"", "", "", "", "", ""}},
        {"readahead", {"int fd", "loff_t offset", "size_t count", "", "", ""}},
        {"setxattr", {"const char *path", "const char *name", "const void *value", "size_t size", "int flags", ""}},
        {"lsetxattr", {"const char *path", "const char *name", "const void *value", "size_t size", "int flags", ""}},
        {"fsetxattr", {"int fd", "const char *name", "const void *value", "size_t size", "int flags", ""}},
        {"getxattr", {"const char *path", "const char *name", "void *value", "size_t size", "", ""}},
        {"lgetxattr", {"const char *path", "const char *name", "void *value", "size_t size", "", ""}},
        {"fgetxattr", {"int fd", "const char *name", "void *value", "size_t size", "", ""}},
        {"listxattr", {"const char *path", "char *list", "size_t size", "", "", ""}},
        {"llistxattr", {"const char *path", "char *list", "size_t size", "", "", ""}},
        {"flistxattr", {"int fd", "char *list", "size_t size", "", "", ""}},
        {"removexattr", {"const char *path", "const char *name", "", "", "", ""}},
        {"lremovexattr", {"const char *path", "const char *name", "", "", "", ""}},
        {"fremovexattr", {"int fd", "const char *name", "", "", "", ""}},
        {"tkill", {"pid_t pid", "int sig", "", "", "", ""}},
        {"sendfile64", {"int out_fd", "int in_fd", "loff_t *offset", "size_t count", "", ""}},
        {"futex", {"u32 *uaddr", "int op", "u32 val", "struct timespec *utime", "u32 *uaddr2", "u32 val3"}},
        {"sched_setaffinity", {"pid_t pid", "unsigned int len", "unsigned long *user_mask_ptr", "", "", ""}},
        {"sched_getaffinity", {"pid_t pid", "unsigned int len", "unsigned long *user_mask_ptr", "", "", ""}},
        {"set_thread_area", {"", "", "", "", "", ""}},
        {"get_thread_area", {"", "", "", "", "", ""}},
        {"io_setup", {"unsigned nr_reqs", "aio_context_t *ctx", "", "", "", ""}},
        {"io_destroy", {"aio_context_t ctx", "", "", "", "", ""}},
        {"io_getevents", {"aio_context_t ctx_id", "long min_nr", "long nr", "struct io_event *events", "struct timespec *timeout", ""}},
        {"io_submit", {"aio_context_t", "long", "struct iocb * *", "", "", ""}},
        {"io_cancel", {"aio_context_t ctx_id", "struct iocb *iocb", "struct io_event *result", "", "", ""}},
        {"fadvise64", {"int fd", "loff_t offset", "size_t len", "int advice", "", ""}},
        {"not implemented", {"", "", "", "", "", ""}},
        {"exit_group", {"int error_code", "", "", "", "", ""}},
        {"lookup_dcookie", {"u64 cookie64", "char *buf", "size_t len", "", "", ""}},
        {"epoll_create", {"int size", "", "", "", "", ""}},
        {"epoll_ctl", {"int epfd", "int op", "int fd", "struct epoll_event *event", "", ""}},
        {"epoll_wait", {"int epfd", "struct epoll_event *events", "int maxevents", "int timeout", "", ""}},
        {"remap_file_pages", {"unsigned long start", "unsigned long size", "unsigned long prot", "unsigned long pgoff", "unsigned long flags", ""}},
        {"set_tid_address", {"int *tidptr", "", "", "", "", ""}},
        {"timer_create", {"clockid_t which_clock", "struct sigevent *timer_event_spec", "timer_t * created_timer_id", "", "", ""}},
        {"timer_settime", {"timer_t timer_id", "int flags", "const struct __kernel_itimerspec *new_setting", "struct itimerspec *old_setting", "", ""}},
        {"timer_gettime", {"timer_t timer_id", "struct __kernel_itimerspec *setting", "", "", "", ""}},
        {"timer_getoverrun", {"timer_t timer_id", "", "", "", "", ""}},
        {"timer_delete", {"timer_t timer_id", "", "", "", "", ""}},
        {"clock_settime", {"clockid_t which_clock", "const struct __kernel_timespec *tp", "", "", "", ""}},
        {"clock_gettime", {"clockid_t which_clock", "struct __kernel_timespec *tp", "", "", "", ""}},
        {"clock_getres", {"clockid_t which_clock", "struct __kernel_timespec *tp", "", "", "", ""}},
        {"clock_nanosleep", {"clockid_t which_clock", "int flags", "const struct __kernel_timespec *rqtp", "struct __kernel_timespec *rmtp", "", ""}},
        {"statfs64", {"const char *path", "size_t sz", "struct statfs64 *buf", "", "", ""}},
        {"fstatfs64", {"unsigned int fd", "size_t sz", "struct statfs64 *buf", "", "", ""}},
        {"tgkill", {"pid_t tgid", "pid_t pid", "int sig", "", "", ""}},
        {"utimes", {"char *filename", "struct timeval *utimes", "", "", "", ""}},
        {"fadvise64_64", {"int fd", "loff_t offset", "loff_t len", "int advice", "", ""}},
        {"vserver", {"", "", "", "", "", ""}},
        {"mbind", {"unsigned long start", "unsigned long len", "unsigned long mode", "const unsigned long *nmask", "unsigned long maxnode", "unsigned flags"}},
        {"get_mempolicy", {"int *policy", "unsigned long *nmask", "unsigned long maxnode", "unsigned long addr", "unsigned long flags", ""}},
        {"set_mempolicy", {"int mode", "const unsigned long *nmask", "unsigned long maxnode", "", "", ""}},
        {"mq_open", {"const char *name", "int oflag", "umode_t mode", "struct mq_attr *attr", "", ""}},
        {"mq_unlink", {"const char *name", "", "", "", "", ""}},
        {"mq_timedsend", {"mqd_t mqdes", "const char *msg_ptr", "size_t msg_len", "unsigned int msg_prio", "const struct __kernel_timespec *abs_timeout", ""}},
        {"mq_timedreceive", {"mqd_t mqdes", "char *msg_ptr", "size_t msg_len", "unsigned int *msg_prio", "const struct __kernel_timespec *abs_timeout", ""}},
        {"mq_notify", {"mqd_t mqdes", "const struct sigevent *notification", "", "", "", ""}},
        {"mq_getsetattr", {"mqd_t mqdes", "const struct mq_attr *mqstat", "struct mq_attr *omqstat", "", "", ""}},
        {"kexec_load", {"unsigned long entry", "unsigned long nr_segments", "struct kexec_segment *segments", "unsigned long flags", "", ""}},
        {"waitid", {"int which", "pid_t pid", "struct siginfo *infop", "int options", "struct rusage *ru", ""}},
        {"not implemented", {"", "", "", "", "", ""}},
        {"add_key", {"const char *_type", "const char *_description", "const void *_payload", "size_t plen", "key_serial_t destringid", ""}},
        {"request_key", {"const char *_type", "const char *_description", "const char *_callout_info", "key_serial_t destringid", "", ""}},
        {"keyctl", {"int cmd", "unsigned long arg2", "unsigned long arg3", "unsigned long arg4", "unsigned long arg5", ""}},
        {"ioprio_set", {"int which", "int who", "int ioprio", "", "", ""}},
        {"ioprio_get", {"int which", "int who", "", "", "", ""}},
        {"inotify_init", {"", "", "", "", "", ""}},
        {"inotify_add_watch", {"int fd", "const char *path", "u32 mask", "", "", ""}},
        {"inotify_rm_watch", {"int fd", "__s32 wd", "", "", "", ""}},
        {"migrate_pages", {"pid_t pid", "unsigned long maxnode", "const unsigned long *from", "const unsigned long *to", "", ""}},
        {"openat", {"int dfd", "const char *filename", "int flags", "umode_t mode", "", ""}},
        {"mkdirat", {"int dfd", "const char * pathname", "umode_t mode", "", "", ""}},
        {"mknodat", {"int dfd", "const char * filename", "umode_t mode", "unsigned dev", "", ""}},
        {"fchownat", {"int dfd", "const char *filename", "uid_t user", "gid_t group", "int flag", ""}},
        {"futimesat", {"int dfd", "const char *filename", "struct timeval *utimes", "", "", ""}},
        {"fstatat64", {"int dfd", "const char *filename", "struct stat64 *statbuf", "int flag", "", ""}},
        {"unlinkat", {"int dfd", "const char * pathname", "int flag", "", "", ""}},
        {"renameat", {"int olddfd", "const char * oldname", "int newdfd", "const char * newname", "", ""}},
        {"linkat", {"int olddfd", "const char *oldname", "int newdfd", "const char *newname", "int flags", ""}},
        {"symlinkat", {"const char * oldname", "int newdfd", "const char * newname", "", "", ""}},
        {"readlinkat", {"int dfd", "const char *path", "char *buf", "int bufsiz", "", ""}},
        {"fchmodat", {"int dfd", "const char * filename", "umode_t mode", "", "", ""}},
        {"faccessat", {"int dfd", "const char *filename", "int mode", "", "", ""}},
        {"pselect6", {"int", "fd_set *", "fd_set *", "fd_set *", "struct timespec *", "void *"}},
        {"ppoll", {"struct pollfd *", "unsigned int", "struct timespec *", "const sigset_t *", "size_t", ""}},
        {"unshare", {"unsigned long unshare_flags", "", "", "", "", ""}},
        {"set_robust_list", {"struct robust_list_head *head", "size_t len", "", "", "", ""}},
        {"get_robust_list", {"int pid", "struct robust_list_head * *head_ptr", "size_t *len_ptr", "", "", ""}},
        {"splice", {"int fd_in", "loff_t *off_in", "int fd_out", "loff_t *off_out", "size_t len", "unsigned int flags"}},
        {"sync_file_range", {"int fd", "loff_t offset", "loff_t nbytes", "unsigned int flags", "", ""}},
        {"tee", {"int fdin", "int fdout", "size_t len", "unsigned int flags", "", ""}},
        {"vmsplice", {"int fd", "const struct iovec *iov", "unsigned long nr_segs", "unsigned int flags", "", ""}},
        {"move_pages", {"pid_t pid", "unsigned long nr_pages", "const void * *pages", "const int *nodes", "int *status", "int flags"}},
        {"getcpu", {"unsigned *cpu", "unsigned *node", "struct getcpu_cache *cache", "", "", ""}},
        {"epoll_pwait", {"int epfd", "struct epoll_event *events", "int maxevents", "int timeout", "const sigset_t *sigmask", "size_t sigsetsize"}},
        {"utimensat", {"int dfd", "const char *filename", "struct timespec *utimes", "int flags", "", ""}},
        {"signalfd", {"int ufd", "sigset_t *user_mask", "size_t sizemask", "", "", ""}},
        {"timerfd_create", {"int clockid", "int flags", "", "", "", ""}},
        {"eventfd", {"unsigned int count", "", "", "", "", ""}},
        {"fallocate", {"int fd", "int mode", "loff_t offset", "loff_t len", "", ""}},
        {"timerfd_settime", {"int ufd", "int flags", "const struct __kernel_itimerspec *utmr", "struct __kernel_itimerspec *otmr", "", ""}},
        {"timerfd_gettime", {"int ufd", "struct __kernel_itimerspec *otmr", "", "", "", ""}},
        {"signalfd4", {"int ufd", "sigset_t *user_mask", "size_t sizemask", "int flags", "", ""}},
        {"eventfd2", {"unsigned int count", "int flags", "", "", "", ""}},
        {"epoll_create1", {"int flags", "", "", "", "", ""}},
        {"dup3", {"unsigned int oldfd", "unsigned int newfd", "int flags", "", "", ""}},
        {"pipe2", {"int *fildes", "int flags", "", "", "", ""}},
        {"inotify_init1", {"int flags", "", "", "", "", ""}},
        {"preadv", {"unsigned long fd", "const struct iovec *vec", "unsigned long vlen", "unsigned long pos_l", "unsigned long pos_h", ""}},
        {"pwritev", {"unsigned long fd", "const struct iovec *vec", "unsigned long vlen", "unsigned long pos_l", "unsigned long pos_h", ""}},
        {"rt_tgsigqueueinfo", {"pid_t tgid", "pid_t pid", "int sig", "siginfo_t *uinfo", "", ""}},
        {"perf_event_open", {"struct perf_event_attr *attr_uptr", "pid_t pid", "int cpu", "int group_fd", "unsigned long flags", ""}},
        {"recvmmsg", {"int fd", "struct mmsghdr *msg", "unsigned int vlen", "unsigned flags", "struct timespec *timeout", ""}},
        {"fanotify_init", {"unsigned int flags", "unsigned int event_f_flags", "", "", "", ""}},
        {"fanotify_mark", {"int fanotify_fd", "unsigned int flags", "u64 mask", "int fd", "const char *pathname", ""}},
        {"prlimit64", {"pid_t pid", "unsigned int resource", "const struct rlimit64 *new_rlim", "struct rlimit64 *old_rlim", "", ""}},
        {"name_to_handle_at", {"int dfd", "const char *name", "struct file_handle *handle", "int *mnt_id", "int flag", ""}},
        {"open_by_handle_at", {"int mountdirfd", "struct file_handle *handle", "int flags", "", "", ""}},
        {"clock_adjtime", {"clockid_t which_clock", "struct timex *tx", "", "", "", ""}},
        {"syncfs", {"int fd", "", "", "", "", ""}},
        {"sendmmsg", {"int fd", "struct mmsghdr *msg", "unsigned int vlen", "unsigned flags", "", ""}},
        {"setns", {"int fd", "int nstype", "", "", "", ""}},
        {"process_vm_readv", {"pid_t pid", "const struct iovec *lvec", "unsigned long liovcnt", "const struct iovec *rvec", "unsigned long riovcnt", "unsigned long flags"}},
        {"process_vm_writev", {"pid_t pid", "const struct iovec *lvec", "unsigned long liovcnt", "const struct iovec *rvec", "unsigned long riovcnt", "unsigned long flags"}},
        {"kcmp", {"pid_t pid1", "pid_t pid2", "int type", "unsigned long idx1", "unsigned long idx2", ""}},
        {"finit_module", {"int fd", "const char *uargs", "int flags", "", "", ""}},
        {"sched_setattr", {"pid_t pid", "struct sched_attr *attr", "unsigned int flags", "", "", ""}},
        {"sched_getattr", {"pid_t pid", "struct sched_attr *attr", "unsigned int size", "unsigned int flags", "", ""}},
        {"renameat2", {"int olddfd", "const char *oldname", "int newdfd", "const char *newname", "unsigned int flags", ""}},
        {"seccomp", {"unsigned int op", "unsigned int flags", "const char *uargs", "", "", ""}},
        {"getrandom", {"char *buf", "size_t count", "unsigned int flags", "", "", ""}},
        {"memfd_create", {"const char *uname_ptr", "unsigned int flags", "", "", "", ""}},
        {"bpf", {"int cmd", "union bpf_attr *attr", "unsigned int size", "", "", ""}},
        {"execveat", {"int dfd", "const char *filename", "const char *const *argv", "const char *const *envp", "int flags", ""}},
        {"socket", {"int", "int", "int", "", "", ""}},
        {"socketpair", {"int", "int", "int", "int *", "", ""}},
        {"bind", {"int", "struct sockaddr *", "int", "", "", ""}},
        {"connect", {"int", "struct sockaddr *", "int", "", "", ""}},
        {"listen", {"int", "int", "", "", "", ""}},
        {"accept4", {"int", "struct sockaddr *", "int *", "int", "", ""}},
        {"getsockopt", {"int fd", "int level", "int optname", "char *optval", "int *optlen", ""}},
        {"setsockopt", {"int fd", "int level", "int optname", "char *optval", "int optlen", ""}},
        {"getsockname", {"int", "struct sockaddr *", "int *", "", "", ""}},
        {"getpeername", {"int", "struct sockaddr *", "int *", "", "", ""}},
        {"sendto", {"int", "void *", "size_t", "unsigned", "struct sockaddr *", "int"}},
        {"sendmsg", {"int fd", "struct user_msghdr *msg", "unsigned flags", "", "", ""}},
        {"recvfrom", {"int", "void *", "size_t", "unsigned", "struct sockaddr *", "int *"}},
        {"recvmsg", {"int fd", "struct user_msghdr *msg", "unsigned flags", "", "", ""}},
        {"shutdown", {"int", "int", "", "", "", ""}},
        {"userfaultfd", {"int flags", "", "", "", "", ""}},
        {"membarrier", {"int cmd", "int flags", "", "", "", ""}},
        {"mlock2", {"unsigned long start", "size_t len", "int flags", "", "", ""}},
        {"copy_file_range", {"int fd_in", "loff_t *off_in", "int fd_out", "loff_t *off_out", "size_t len", "unsigned int flags"}},
        {"preadv2", {"unsigned long fd", "const struct iovec *vec", "unsigned long vlen", "unsigned long pos_l", "unsigned long pos_h", "rwf_t flags"}},
        {"pwritev2", {"unsigned long fd", "const struct iovec *vec", "unsigned long vlen", "unsigned long pos_l", "unsigned long pos_h", "rwf_t flags"}},
        {"pkey_mprotect", {"unsigned long start", "size_t len", "unsigned long prot", "int pkey", "", ""}},
        {"pkey_alloc", {"unsigned long flags", "unsigned long init_val", "", "", "", ""}},
        {"pkey_free", {"int pkey", "", "", "", "", ""}},
        {"arch_prctl", {"", "", "", "", "", ""}},
        {"statx", {"int dfd", "const char *path", "unsigned flags", "unsigned mask", "struct statx *buffer", ""}},
};
#else
const system_call_information syscalls_info[SYSCALLS_QUANTITY];
#endif
#endif

#endif //TAREA2_CONSTANTS_H
